### PR TITLE
Added Function to variable out SQD Info

### PR DESCRIPTION
**Pull request by Cabur**

### CODE REVIEW

**Comment by Duckmanjbr** [comment]
Do you want this to prompt every time you run it?  Normally this will only be set one time and then just rerun multiple times.  Seems like a extra key strokes for a onetime change.

**Comment by Cabur** [comment]
Hmm...they know that then sure. Might revist it later, but I'll do another pull req.

**Comment by Duckmanjbr** [comment]
I also updated the sensor_config.sh just now.

**Comment by Duckmanjbr** [comment]
I'll add it and just throw in an option to change.  You ok with that?

**Comment by Cabur** [comment]
Naw just dump it. I'm thinking more along the lines of default/empty viariables the kill the script if not changed. So they do only set it once

**Comment by Duckmanjbr** [comment]
Roger!  I’m working pfSense now.  :)

**Comment by Cabur** [comment]
Added the check for SQD Numbers, I left out SQD Name cause it wasn't working like it should. I revisit it. also it doesn't seem to be needed other than in the mainmenu function as display...unless im mission something

**Review by Duckmanjbr — APPROVED** [review]
Works for me!

**Pull request merged**
